# Generated by Django 5.1.3 on 2025-10-31 21:16

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("resume", "Resume"),
                            ("transcript", "Transcript"),
                            ("certificate", "Certificate"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of document",
                        max_length=20,
                        verbose_name="document type",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload document file",
                        upload_to=documents.models.user_document_path,
                        verbose_name="file",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original name of the uploaded file",
                        max_length=255,
                        verbose_name="original filename",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="uploaded at"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="File size in bytes",
                        null=True,
                        verbose_name="file size",
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the document has been processed for information extraction",
                        verbose_name="is processed",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when document was processed",
                        null=True,
                        verbose_name="processed at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who uploaded this document",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "document",
                "verbose_name_plural": "documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ExtractedInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("name", "Name"),
                            ("email", "Email"),
                            ("education", "Education"),
                            ("experience", "Work Experience"),
                            ("skills", "Skills"),
                            ("certifications", "Certifications"),
                        ],
                        help_text="Type of extracted data",
                        max_length=20,
                        verbose_name="data type",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        help_text="Extracted information stored as JSON",
                        verbose_name="content",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score of the extraction (0.0 to 1.0)",
                        verbose_name="confidence score",
                    ),
                ),
                (
                    "extracted_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="extracted at"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        help_text="Document from which information was extracted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_info",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "extracted information",
                "verbose_name_plural": "extracted information",
                "ordering": ["-extracted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["user", "document_type"], name="documents_d_user_id_9276f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["is_processed"], name="documents_d_is_proc_e16fac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["user", "is_processed"], name="documents_d_user_id_99aae3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractedinformation",
            index=models.Index(
                fields=["document", "data_type"], name="documents_e_documen_61a969_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="extractedinformation",
            index=models.Index(
                fields=["data_type"], name="documents_e_data_ty_c6df3a_idx"
            ),
        ),
    ]
