# Generated by Django 5.1.3 on 2025-10-31 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("job", "Job Application"),
                            ("scholarship", "Scholarship Application"),
                        ],
                        help_text="Type of application (job or scholarship)",
                        max_length=20,
                        verbose_name="application type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Job title or scholarship name",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "company_or_institution",
                    models.CharField(
                        help_text="Company name or educational institution",
                        max_length=200,
                        verbose_name="company or institution",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Application URL or posting link",
                        max_length=500,
                        verbose_name="URL",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Job or scholarship description",
                        verbose_name="description",
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True,
                        help_text="Application deadline",
                        null=True,
                        verbose_name="deadline",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("in_review", "In Review"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        help_text="Current application status",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        help_text="Application priority level",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when application was submitted",
                        null=True,
                        verbose_name="submitted at",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or comments",
                        verbose_name="notes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this application",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "application",
                "verbose_name_plural": "applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("in_review", "In Review"),
                            ("interview", "Interview"),
                            ("offer", "Offer"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        help_text="New status value",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "changed_by",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Update"),
                            ("ai_detected", "AI Detected"),
                            ("user_update", "User Update"),
                        ],
                        default="manual",
                        help_text="How the status was changed",
                        max_length=20,
                        verbose_name="changed by",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about the status change",
                        verbose_name="notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        help_text="Application whose status changed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="tracker.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "application status",
                "verbose_name_plural": "application statuses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.TextField(
                        help_text="The question or prompt text",
                        verbose_name="question text",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("short_answer", "Short Answer"),
                            ("essay", "Essay"),
                            ("experience", "Work Experience"),
                            ("education", "Education"),
                            ("skills", "Skills"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        help_text="Type of question",
                        max_length=20,
                        verbose_name="question type",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this question is required",
                        verbose_name="is required",
                    ),
                ),
                (
                    "is_extracted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this question was auto-extracted from application",
                        verbose_name="is extracted",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order of the question",
                        verbose_name="order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        help_text="Application this question belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="tracker.application",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ["application", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated_response",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated response text",
                        verbose_name="generated response",
                    ),
                ),
                (
                    "edited_response",
                    models.TextField(
                        blank=True,
                        help_text="User-edited version of the response",
                        null=True,
                        verbose_name="edited response",
                    ),
                ),
                (
                    "is_ai_generated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether response was generated by AI",
                        verbose_name="is AI generated",
                    ),
                ),
                (
                    "generation_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Prompt used to generate AI response",
                        verbose_name="generation prompt",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When AI response was generated",
                        null=True,
                        verbose_name="generated at",
                    ),
                ),
                (
                    "last_edited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When response was last edited",
                        null=True,
                        verbose_name="last edited at",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Version number for tracking edits",
                        verbose_name="version",
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        help_text="Question this response answers",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="tracker.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "response",
                "verbose_name_plural": "responses",
                "ordering": ["question"],
            },
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["user", "status"], name="tracker_app_user_id_2c6ffc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["deadline"], name="tracker_app_deadlin_2b0780_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["created_at"], name="tracker_app_created_4620d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["user", "application_type"],
                name="tracker_app_user_id_40bc3c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationstatus",
            index=models.Index(
                fields=["application", "-created_at"],
                name="tracker_app_applica_7701c6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["application", "order"], name="tracker_que_applica_492880_idx"
            ),
        ),
    ]
