# Generated by Django 4.2.25 on 2025-11-07 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0003_add_tags_interviews_referrals_archive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag_per_user',
        ),
        migrations.RenameIndex(
            model_name='interview',
            new_name='tracker_int_applica_1a306e_idx',
            old_name='tracker_int_app_date_idx',
        ),
        migrations.RenameIndex(
            model_name='interview',
            new_name='tracker_int_user_id_20d67a_idx',
            old_name='tracker_int_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='interview',
            new_name='tracker_int_status_140530_idx',
            old_name='tracker_int_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='tracker_not_user_id_047757_idx',
            old_name='tracker_not_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='tracker_not_applica_03af8c_idx',
            old_name='tracker_not_applica_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='tracker_not_user_id_f7a104_idx',
            old_name='tracker_not_user_ap_idx',
        ),
        migrations.RenameIndex(
            model_name='referral',
            new_name='tracker_ref_applica_307234_idx',
            old_name='tracker_ref_app_date_idx',
        ),
        migrations.RenameIndex(
            model_name='referral',
            new_name='tracker_ref_user_id_b07541_idx',
            old_name='tracker_ref_user_date_idx',
        ),
        migrations.RenameIndex(
            model_name='tag',
            new_name='tracker_tag_user_id_0f17bb_idx',
            old_name='tracker_tag_user_name_idx',
        ),
        migrations.AlterField(
            model_name='application',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for organizing and categorizing applications', related_name='applications', to='tracker.tag', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Expected duration of the interview in minutes', verbose_name='duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('phone', 'Phone Interview'), ('video', 'Video Interview'), ('onsite', 'Onsite Interview'), ('panel', 'Panel Interview')], help_text='Type of interview', max_length=20, verbose_name='interview type'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.TextField(blank=True, help_text='Physical location for onsite interviews', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the interview (preparation, topics, feedback)', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='scheduled_date',
            field=models.DateTimeField(help_text='Date and time of the interview', verbose_name='scheduled date'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', help_text='Current status of the interview', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='user',
            field=models.ForeignKey(help_text='User who created this interview', on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the interviewer', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='name',
            field=models.CharField(help_text='Full name of the interviewer', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the interviewer', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number of the interviewer', max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='interviewer',
            name='title',
            field=models.CharField(help_text='Job title/position of the interviewer', max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='company',
            field=models.CharField(help_text='Company where the referrer works', max_length=200, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='email',
            field=models.EmailField(help_text='Email address of the referrer', max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='name',
            field=models.CharField(help_text='Name of the person providing the referral', max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the referral', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number of the referrer', max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_date',
            field=models.DateField(help_text='Date when the referral was made', verbose_name='referred date'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='relationship',
            field=models.CharField(help_text='Your relationship to the referrer (e.g., former colleague, friend, mentor)', max_length=200, verbose_name='relationship'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.ForeignKey(help_text='User who received this referral', on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#6366f1', help_text='Hex color code for the tag (e.g., #6366f1)', max_length=7, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Tag name (e.g., Remote, High Salary, Dream Company)', max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(help_text='User who created this tag', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
    ]
