# Generated by Django 5.1.3 on 2025-10-31 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reminder", "Reminder"),
                            ("status_change", "Status Change"),
                            ("system", "System Notification"),
                        ],
                        help_text="Type of notification",
                        max_length=20,
                        verbose_name="notification type",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Notification title",
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Notification message content", verbose_name="message"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional link related to notification",
                        max_length=500,
                        null=True,
                        verbose_name="link",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether notification has been read",
                        verbose_name="is read",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When notification was read",
                        null=True,
                        verbose_name="read at",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User to notify",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("deadline", "Deadline Reminder"),
                            ("follow_up", "Follow-up Reminder"),
                            ("interview", "Interview Reminder"),
                            ("custom", "Custom Reminder"),
                        ],
                        default="custom",
                        help_text="Type of reminder",
                        max_length=20,
                        verbose_name="reminder type",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Reminder message text", verbose_name="message"
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        help_text="When to send this reminder",
                        verbose_name="scheduled for",
                    ),
                ),
                (
                    "is_sent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether reminder has been sent",
                        verbose_name="is sent",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When reminder was sent",
                        null=True,
                        verbose_name="sent at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "application",
                    models.ForeignKey(
                        help_text="Application this reminder is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="tracker.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User to be reminded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "reminder",
                "verbose_name_plural": "reminders",
                "ordering": ["scheduled_for"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_sent"],
                        name="notificatio_user_id_991809_idx",
                    ),
                    models.Index(
                        fields=["scheduled_for"], name="notificatio_schedul_3730cb_idx"
                    ),
                    models.Index(
                        fields=["is_sent", "scheduled_for"],
                        name="notificatio_is_sent_9b4201_idx",
                    ),
                ],
            },
        ),
    ]
