# Generated by Django 4.2.25 on 2025-11-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('status_change', 'Status Change'), ('deadline', 'Deadline Alert'), ('document', 'Document Processed'), ('system', 'System Notification')], help_text='Type of notification', max_length=20, verbose_name='notification type'),
        ),
    ]
